catalog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    
]

shiksha/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import uuid
from datetime import date


# Create your models here.

class Book(models.Model):
  title = models.CharField(max_length = 200)
  author = models.ForeignKey('Author', on_delete=models.RESTRICT,null =True)
  summary = models.TextField(max_length = 900, help_text = 'Enter a brief description here')
  isbn = models.CharField('ISBN', max_length = 200, unique = True, help_text = '13 Character <a href="https://www.isbn-international.org/content/what-isbn'
   '">ISBN number</a>')
  genre = models.ManyToManyField('Genre', help_text = "Select a genre for this book")
  #language = models.ForeignKey('Language', on_delete =models.RESTRICT, null = True)
 
  def __str__(self):
    return f"{self.title}"

  def get_absolute_url(self):
    return reverse('book-detail', args=[str(self.id)])

  def display_genre(self):
    return ','.join(genre.name for genre in self.genre.all()[:2])
    display_genre.short_description = 'Genre'  


class Book_Copy_Info(models.Model):

    id = models.UUIDField(primary_key=True, default = uuid.uuid4,help_text = "Unique ID for this book")
    book = models.ForeignKey('Book', on_delete = models.RESTRICT, null =True)
    imprint = models.CharField(max_length = 200)
    due_back = models.DateField(null =True, blank =True)
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)



    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)



    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length = 1, choices = LOAN_STATUS, blank= True, default = 'm', help_text = 'Choose book availability status',)
    
    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set Book as Returned'),)

    def __str__(self):
      return f"({self.book.title}) {self.status} {self.due_back} {self.id}"
      
class Author(models.Model):
  first_name = models.CharField(max_length = 100)
  last_name = models.CharField(max_length =100)
  date_of_birth = models.DateField(null = True, blank = True)
  date_of_death = models.DateField('Died', null = True, blank =True)

  class Meta :
    ordering = ['last_name','first_name']
     
  def __str__(self) :
      return f"{self.last_name}, {self.first_name}"

  def get_absolute_url(self):
    return reverse('author-detail', args = [str(self.id)])  

class Genre(models.Model):
  name = models.CharField(max_length = 200, unique=True , help_text = "Enter this book's genre" )
   
  def __str__(self):
    return f"{self.name}"

  def get_absolute_url(self):
    return reverse('genre-detail', args = [str(self.id)])

class Language(models.Model):
  SELECT_LANGUAGE = (
    ('e','English'),
    ('h','Hindi'),
    ('u','Urdu'),
    ('f','Farsi'),
         )
  language_name = models.CharField(max_length =200, choices =SELECT_LANGUAGE ,
  blank=True)

  def __str__(self):
    return f"{self.language_name}"

  def get_absolute_url(self):
    return reverse('language-detail', args =[str(self.id)])

catalog/forms.py
from django.forms import ModelForm
from catalog.models import Book_Copy_Info

class BookRenewForm(ModelForm):
    data = self.cleaned_data['due_back']

    if data < datetime.date.today():
           raise ValidationError(_('book cannot be due int the past, Please enter a valid date'))
    if data > datetime.date.today() + datetime.timedelta(weeks =3 ):
        raise ValidationError(_('Please enter a date between today and 3 weeks'))

    return data


    class Meta:
        model = Book_Copy_Info
        fields = ['due_back']
        

catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import BookRenewForm

# Create your views here.

from .models import Book,Book_Copy_Info,Language,Genre,Author
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    total_num_books = Book.objects.count()
    total_num_Book_Copy_Info = Book_Copy_Info.objects.count()
    total_num_Book_Copy_Info_avail = Book_Copy_Info.objects.filter(status__exact = 'a').count()
    total_num_authors = Author.objects.count()
    total_num_genres = Genre.objects.count()

    context = {
        'total_num_books' : total_num_books,
        'total_num_Book_Copy_Info' : total_num_Book_Copy_Info,
        'total_num_Book_Copy_Info_avail' : total_num_Book_Copy_Info_avail,
        'total_num_authors' : total_num_authors,
        'total_num_genres' : total_num_genres,
        

    }

    return render(request, 'index.html', context = context)


class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book    


class AuthorListView(generic.ListView):
    model = Author
    
class AuthorDetailView(generic.DetailView):
    model = Author




class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = Book_Copy_Info
    template_name = 'catalog/borrowed_books.html'
    

    def get_queryset(self):
        return (
           Book_Copy_Info.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


def renew_books(request,pk):
    Book_Copy_Info = get_object_or_404(Book_Copy_Info,pk=pk)

    if request.Method == 'POST':
        filled_form = BookRenewForm(request.POST)

    if form.is_valid():
      Book_Copy_Info_form_due_back = form.cleaned_data['due_back']
      Book_Copy_Info_form_due_back.save()

      return HttpResponseRedirect(reverse('my-borrowed'))


    else:
      proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
      form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

context = {
    'form': form,
    'Book_Copy_Info': Book_Copy_Info,
}

return render(request, 'catalog/book_renew_librarian.html', context)
 

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}
    <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'books' %}">All Books</a></li>
                    <li><a href=" {% url 'authors' %}">All authors</a></li>

                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}

                </ul>

                {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>

                <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>

                <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                {% endif %}
                </ul>

                {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
        </div>
    </div>
</body>

</html>

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author Details are below :</h1>
<h2> Author : {{author.first_name}} {{author.last_name}}</h2>

<p> Author's DOB : {{author.date_of_birth}} </p>
<div style="margin-left:20px;margin-top:20px">
    <h4> Books written: </h4>
    <dl>
        {% for book in author.book_set.all %}
        <dt> <a href="{{book.get_absoliute_url}}" {{book.title}}></a></dt>
        {% empty %}
        <p> Sorry, we don't have any books from this author yet</p>
        {% endfor % }
    </dl>


</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author List</h1>
{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        <strong>Author's Full Name:<a href="{{author.get_absolute_url}}"></strong>{{author.first_name}}
        {{author.last_name}}.</a>

    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no authors currently in the library, we are working on getting some amazing authors on board.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="book.author.get_absolute_url">{{ book.author }}</a></p>
<!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Available Copies</h4>

    {% for copy in book.book_copy_info_set.all %}
    <hr />
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}"> {{book.title}} ({{book.author}}) </a>
    </li>
    {% empty %}
    <p> Sorry! There are no books available</p>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

catalog/templates/catalog/borrowed_books.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>

{% if book_Copy_Info_list %}
<ul>

    {% for copy in book_Copy_Info_list.is_overdue %}text-danger{% endif %}">
    <a href="{% url 'book-detail' book_Copy_Info.book.pk %}">{{ book_Copy_Info.book.title }}</a>
    ({{ book_Copy_Info.due_back }})
    </li>
    {% endfor %}
</ul>

{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}
{% block title %}
<title> Shiksha</title>
{% endblock %}
{% block content %}
<h1> Welcome to Shiksha</h1>
<p>
    A library for the people who want to improve spiritually & financially. Shiksha is your go to library for
    all things leading to your spiritual awakening and financial freedom.
</p>
<h2>Important facts</h2>
<p>The library has the following record counts:</p>
<ul>
    <li><strong>Total Books:</strong> {{ total_num_books }}</li>
    <li><strong>Total available imprints:</strong> {{ total_num_Book_Copy_Info }}</li>
    <li><strong>Copies available:</strong> {{ total_num_Book_Copy_Info_avail }}</li>
    <li><strong>Authors:</strong> {{total_num_authors}}</li>
    <li><strong>Total Genres: </strong>{{total_num_genres}}
</ul>
{% endblock %}

templates/logout.html
{% extends "base_generic.html" %}

{% block content %}
<p>Logged out!</p>
<a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

templates/password.reset.confirm.email.html
{% extends "base_generic.html" %}

{% block content %}
{% if validlink %}
<p>Please enter (and confirm) your new password.</p>
<form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.new_password1.errors }}
                <label for="id_new_password1">New password:</label></td>
            <td>{{ form.new_password1 }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password2.errors }}
                <label for="id_new_password2">Confirm password:</label></td>
            <td>{{ form.new_password2 }}</td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Change my password"></td>
        </tr>
    </table>
</form>
{% else %}
<h1>Password reset failed</h1>
<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
</p>
{% endif %}
{% endblock %}

templates/password.reset.email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/password.reset.finally.complete.email.html
{% extends "base_generic.html" %}

{% block content %}
<h1>The password has been changed!</h1>
<p><a href="{% url 'login' %}">log in again?</a></p>
{% endblock %}

templates/password.reset.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% if form.email.errors %}
    {{ form.email.errors }}
    {% endif %}
    <p>{{ form.email }}</p>
    <input type="submit" class="btn btn-default btn-lg" value="Reset password">
</form>
{% endblock %}